# Generated by Django 3.2.20 on 2023-08-02 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_contact_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='descc',
        ),
    ]
