# Generated by Django 3.2.20 on 2023-08-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_desc_contact_descc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='descc',
        ),
    ]
